name: Build & Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  NEXT_PUBLIC_SERVER_URL: http://localhost:3000

jobs:
  build-test:
    name: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.4.0
      - run: bun install --frozen-lockfile
      - run: bun run check-types
      - run: bun run lint
      - run: bun run build
      - run: bun run test
